version: '3'

services:

    ireceptor-database:
        image: ireceptor/repository-mongodb:${DATABASE_TAG:-turnkey-v3}
        volumes:
            - ../.mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: ireceptor
        ports:
            - 27017:27017

    ireceptor-api:
        depends_on:
            - ireceptor-database
        build: ../ireceptor-api
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence
        ports:
            - ${API_PORT:-80}:80

    ireceptor-dataloading:
        depends_on:
            - ireceptor-database
        build: ../ireceptor-dataloading
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
        volumes:
            - ${FILE_FOLDER:-/tmp}:/scratch

    ireceptor-performance-testing:
        image: ireceptor/dataloading-mongo:${PERFORMANCE_TESTING_TAG:-turnkey-v3-performance}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence
